obstacle_range: 4
raytrace_range: 6
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.1
inflation_radius: 0.12
cost_scaling_factor: 1.5

observation_sources: laser_scan_sensor #sensor2

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#sensor2: {sensor_frame: laser, data_type: LaserScan, topic: scan2, marking: true, clearing: true}
