obstacle_range: 2.0
raytrace_range: 2.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.15
inflation_radius: 1.0 #0.12
cost_scaling_factor: 3.0 #1.5
combination_method: 1
transform_tolerance: 2.0

observation_sources: laser_scan_sensor #sensor2

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 0.3}
#expected_update_rate: 5.0, observation_persistence: 0.0, min_obstacle_height: 0.0, max_obstacle_height: 2.0}

#sensor2: {sensor_frame: laser, data_type: LaserScan, topic: scan2, marking: true, clearing: true}
