global_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 12.0
  height: 12.0
  resolution: 0.1
  origin_x: 0
  origin_y: 0
  transform_tolerance: 2.0
