global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false
  width: 30.0
  height: 30.0
  resolution: 0.1
  origin_x: -15.0
  origin_y: -15.0
  transform_tolerance: 2.0
  always_send_full_costmap: true
